$stdout.print "out1"
$stderr.print "err1"
$stdout.print "out2"
$stdout.print "out3"
$stdout.print "err2\n"
$stdout.print "out4\n"

$stdout.print "err2\n"
$stdout.print "out4\n"
$stdout.print "err2\n"
$stdout.print "out4\n"
$stdout.print "err2\n"
$stdout.print "out4\n"
$stdout.print "err2\n"
$stdout.print "out4\n"
$stdout.print "err2\n"
$stdout.print "out4\n"
$stdout.print "err2\n"
$stdout.print "out4\n"
$stdout.print "err2\n"
$stdout.print "out4\n"
$stdout.print "err2\n"
$stdout.print "out4\n"
$stdout.print "err2\n"
$stdout.print "out4\n"

